### PR TITLE
Fixed Organizations word mispelling

### LINKED ISSUE #831: Mispelling 'organizations'
## Steps to Reproduce
1.  Go to an area page without a local climbing organization (https://openbeta.io/crag/a354b580-870b-5444-9f11-2c0e78995841)
2. Scroll down to Local Climbing Organizations section. The below misspells 'organizations': 

## Screenshots

Screenshot 2023-05-18 at 7 04 54 AM

### PR DESCRIPTION
**Pull request by giri-madhan**
### **Scope of change:** 
- Fixed the misspelling in the word Organizations.
### **Screenshots**
After the fix: 
image
### **Notes**
This fixes #831

### CODE REVIEW

**Review by actuallyyun — APPROVED** [review]
Thank you for fixing it!

**Comment by giri-madhan** [comment]
Welcome @actuallyyun !

**Comment by vnugent** [comment]
@all-contributors add @giri-madhan for code

**Comment by giri-madhan** [comment]
Thank you guys!

**Pull request merged**
