### PR TITLE
Add drag n drop reordering of routes

### LINKED ISSUE #409: Allow authenticated users to update left-to-right order of climbs
### Use case
Left-to-right order helps identifying climbs.  As an authenticated user I want to correct the order of climbs at a crag.

https://tacos.openbeta.io/crag/6408df92-375d-5c40-a0ac-010fd2b69a69 

### Todo:
- [ ] Build a reordering component accessible from the crag page
- [ ] Make sure component is responsive on smaller screens
- [ ] Allow the user to drag to rearrange items (update leftToRight index)
- [ ] Add Save and Reset button
- [ ] Wire Save button to backend API (TBD later)

Please provide a mockup.

### PR DESCRIPTION
**Pull request by nthh**
Fixes #409 

[Example Crag](https://open-tacos-87skueby6-openbeta-dev.vercel.app/crag/1e37cc9d-c235-5f67-9bd9-d3b02b9d55e2)

Started this task, just need to fix button styling/location and add the backend part

When editing, I removed the summary of the climb and on all screen sizes make the crag list only have one column 

For the dnd library, I just found the one [here](https://github.com/search?q=react+drag) that had the most stars. It has a lot of boilerplate but seems to work well.

- [x] Build a reordering component accessible from the crag page
- [x] Make sure component is responsive on smaller screens
- [x] Allow the user to drag to rearrange items (update leftToRight index)
- [x] Add Save and Reset button
- [ ] Wire Save button to backend API (TBD later)

### CODE REVIEW

**Comment by vnugent** [comment]
Thanks for starting on this. 

DnD works on on my mobile.  On my laptop (Chrome and Brave) it won't let me DnD.

Also, can you please add the `useCanary()` hook to the page to conditionally render the Change Order button when the canary flag is set `https://tacos.openbeta.io/?next=true`

**Comment by nthh** [comment]
> DnD works on on my mobile. On my laptop (Chrome and Brave) it won't let me DnD.

It works fine for me on mobile, as well as desktop (Mac with Safari/Chrome/Firefox). What OS are you using? 


> Also, can you please add the `useCanary()` hook`

Done

Also, @vnugent what are the next steps to wire it up to the backend?

**Comment by vnugent** [comment]
It's working now (I'm on Mac).  Strange!

The backend is nowhere near ready.  Meanwhile can you look into adding the same reordering for areas in another PR?

**Comment by nthh** [comment]
@vnugent For areas, do you mean a page like [this one](https://tacos.openbeta.io/areas/4ad46886-23a1-59a3-8223-db04c1590476)? If applied to all areas, what about areas such as [the US](https://tacos.openbeta.io/areas/47667307-c0a0-5f50-873d-2a5c6d757fb2) that should not be sortable? Or should all areas be sortable?

**Comment by vnugent** [comment]
I didn't think about the US.  I guess technically we can let users sort US states or we can disable the option. 

In some areas it make sense to sort crags left to right since they're physically next to one another.

I'm familiar with Smith Rock and you can see name prefix (a) (b) (c) ... is used for ordering.  Eventually we will clean up those prefixes and rely on left-to-right order.

https://tacos.openbeta.io/areas/f3c655b6-9c95-597f-aaa6-fd7d8a4865ec

**Comment by vnugent** [comment]
By the way, don't feel constrained to the split screen layout of the area page.  I think we're likely going to change the layout now that we have the map on the main page.

**Pull request merged**
