### PR TITLE
[wip]feat:lco profile card ui

### PR DESCRIPTION
**Pull request by actuallyyun**
- web

Screenshot 2023-04-20 at 09 53 34

- mobile
Screenshot 2023-04-20 at 09 55 26

Hi @vnugent ~
- Since we have not decided how to show lco card, I put it on the page for now to see how it looks. 
- currently missing lco description, social sites, logo data, so I hard-coded it
- Figma design doesn't have specs for the buttons. Could you point to me some references? In particular background color for these two buttons.

Thank you!

### CODE REVIEW

**Comment by vnugent** [comment]
How about using `btn-solid` for the primary call-to-action and `btn-outline` for secondary action?

```javascript
<a className='btn btn-primary btn-outline' href="..." >Make a Donation</a>
<a className='btn btn-primary btn-solid' href="..">Report bad hardware</a>
```

DaisyUI button: https://daisyui.com/components/button/

PS: For future PRs you can clone this repo and push to it directly now that you're in the core contributors group with elevated trust.  This way Vercel will build and deploy the preview instance without requiring an approval from the project maintainer.  Thank you!

**Comment by actuallyyun** [comment]
I was about to ask if I could push directly from this repo. Good to know! 
And thanks for the button idea.

**Comment by actuallyyun** [comment]
Hi @vnugent  have we decided how to show lco card? With hover or click?

**Comment by actuallyyun** [comment]
Use a new PR that is pushed directly to this repo.

**Pull request closed without merging**
