### PR TITLE
Integrate @openbeta/sandbag

### PR DESCRIPTION
**Pull request by gibboj**

### CODE REVIEW

**Comment by vnugent** [comment]
to use vercel we're restricted to node v14

https://github.com/vercel/community/discussions/37

**Comment by gibboj** [comment]
> to use vercel we're restricted to node v14
> 
> [vercel/community#37](https://github.com/vercel/community/discussions/37)

Oh boo. Ok.

**Comment by vnugent** [comment]
I guess you can't see vercel log

```
...
[2/4] Fetching packages...
--
12:53:52.961 | error @openbeta/sandbag@0.0.2: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.3"
12:53:52.961 | error Found incompatible module.
12:53:52.961 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:53:52.988 | Error: Command "yarn install --no-progress" exited with 1



```

**Comment by vnugent** [comment]
Let me try to bump sandbag version in your PR/branch to 0.0.4

**Comment by vnugent** [comment]
Blocked by: https://github.com/OpenBeta/sandbag/issues/18

**Comment by vnugent** [comment]
Can you bump sandbag version to 0.0.10?  I relaxed its node version check to only >=14 (instead of 14.x.x)

**Comment by gibboj** [comment]
> Can you bump sandbag version to 0.0.10? I relaxed its node version check to only >=14 (instead of 14.x.x)

I tried it, the npm package doesn't have the built files in it.

**Pull request merged**
