### PR TITLE
fix: use `100vw` for `sizes` attribute in ResponsiveImage handler

### LINKED ISSUE #1206: Full size image not loading when opening full size image in PhotoGalleryModal
## Steps to Reproduce

1.
2.
3.

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

### PR DESCRIPTION
**Pull request by julianlam**
During an area editing refactor (48acddda6c84803566a54e935e7ac35251d0c21c), a change was made that altered the `sizes` attribute from `100vw` to `20vw`.

This causes issues with images in the climb gallery; the browser chooses the wrong size.

e.g. given the `srcset` as follows:

```
srcset="https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=128&q=75 128w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=256&q=75 256w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=384&q=75 384w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=640&q=75 640w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=750&q=75 750w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=828&q=75 828w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=1080&q=75 1080w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=1200&q=75 1200w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=1920&q=75 1920w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=2048&q=75 2048w,
 https://media.openbeta.io/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/7pmtjHGW76.png?w=3840&q=75 3840w"
```

... and a resolution of 1080x2340 (Google Pixel 5), if `sizes` is `20vw`, then the browser will choose the image just larger than 218px, which is the 384px image. The 1200px image should be the correct selection.

This pull request restores the `sizes` attribute to `100vw` so the `srcset` calculation and selection is correct.

### CODE REVIEW

**Comment by julianlam** [comment]
On production, this is what opening an image looks like on my phone:

Screenshot_20241108-004829

This PR will load the proper size so the text is readable.

**Review by Vichy97 — APPROVED** [review]

**Comment by julianlam** [comment]
Screenshot_20241108-104915

This is what it looks like with the PR applied.

**Review by clintonlunn — COMMENTED** [review]
@julianlam if you add the `sizes` attribute of the `<ResponsiveImage />` in the `<PhotoGalleryModal />` component it has the same effect. Perhaps we should add that property instead of changing the default behavior that was added? 

https://github.com/OpenBeta/open-tacos/blob/4f4c7bac00122ff67e7e64e4cea812a7d8ae615f/src/components/media/PhotoGalleryModal.tsx#L61

**Comment by julianlam** [comment]
I do not know why the attribute value was changed to `20vw` (was hoping @vnugent could provide some context). I'll take a look at the `PhotoGalleryModal`

**Comment by julianlam** [comment]
@clintonlunn done :+1:

**Review by clintonlunn — APPROVED** [review]

**Pull request merged**
