### PR TITLE
Sitemaps.xml

### PR DESCRIPTION
**Pull request by Downster**
Added a dynamically created sitemaps.xml component in pages. Creates the sitemaps.xml file at /sitemap.xml

### CODE REVIEW

**Comment by vnugent** [comment]
Looks great!  Is it possible to add a static url?  such as https://tacos.openbeta.io/about?  we only have 1 but there may be more in the future.

**Comment by vnugent** [comment]
@all-contributors add @Downster for code

**Comment by Downster** [comment]
> Looks great! Is it possible to add a static url? such as https://tacos.openbeta.io/about? we only have 1 but there may be more in the future.

Sure thing, I can add that. It also looks like there was one for Terms of service, would you like me to add that aswell? 

Originally I had it generating the static url's dynamically but it was adding a lot of url's that didn't exist, so I just took it out. I'll have to dive in a little further and see if I can get it to work as intended.

**Comment by vnugent** [comment]
can you also remove the extra / in front of areas?

```
<loc>https://tacos.openbeta.io//areas/decc1251-4a67-52b9-b23f-3243e10e93d0</loc>
```

https://tacos.openbeta.io/sitemap.xml

> there was one for Terms of service, would you like me to add that as well?

The ToS page is not done yet.  We can it later.

**Comment by Downster** [comment]
Yeah, of course!

**Pull request merged**
