### PR TITLE
GradeBands / GradeScales logic from openbeta-graphql to @openbeta/sandbag

### LINKED ISSUE #168: GradeBands / GradeScales logic into @openbeta/sandbag
It would be more appropriate to keep logic relating to scoring / gradescales / gradebands within the @openbeta/sandbag repo.

Move the getBand/score logic out of openbeta-graphql into sandbag repo, so there's a single source of truth.
- https://github.com/OpenBeta/openbeta-graphql/blob/1c5c6f38c0c982bf3f58b9bb985d67800a3717f9/src/grade-utils.ts#L36

Move grade scales out of openbeta-graphql into sandbag repo, so there's a single source of truth.
- https://github.com/OpenBeta/openbeta-graphql/blob/1c5c6f38c0c982bf3f58b9bb985d67800a3717f9/src/grade-utils.ts#L22

### PR DESCRIPTION
**Pull request by DarrenZLew**
- Update open-tacos with new GradeScales from @openbeta/sandbag to help fix https://github.com/OpenBeta/openbeta-graphql/issues/168

This PR is linked to the changes made from https://github.com/OpenBeta/sandbag/pull/76 and https://github.com/OpenBeta/openbeta-graphql/pull/174

To test:
Checkout the @openbeta/sandbag (https://github.com/OpenBeta/sandbag/pull/76) PR branch locally and run 'yarn link'
Then go into this PR and run 'yarn link "@openbeta/sandbag"'

### CODE REVIEW

**Comment by vnugent** [comment]
Do I need to merge https://github.com/OpenBeta/sandbag/pull/76 first in order for the build to compile?

**Comment by DarrenZLew** [comment]
> Do I need to merge [OpenBeta/sandbag#76](https://github.com/OpenBeta/sandbag/pull/76) first in order for the build to compile?

I think that does need to happen first, which it looks like you did merge it. It seems like something else is going on though, so I can take a look at what's going on later tonight.

**Comment by DarrenZLew** [comment]
> > Do I need to merge [OpenBeta/sandbag#76](https://github.com/OpenBeta/sandbag/pull/76) first in order for the build to compile?
> 
> I think that does need to happen first, which it looks like you did merge it. It seems like something else is going on though, so I can take a look at what's going on later tonight.

From looking at what the latest npm version is for @openbeta/sandbag, it is on 0.0.30. The latest changes, which is on 0.0.31 haven't been published yet. We should see whether these builds succeed after the new version has been released.

**Comment by vnugent** [comment]
Sorry I thought I triggered a npm publish but I didn't.  Sandbag is now version 0.0.33.  Can you update package.json and push again?

**Comment by vnugent** [comment]
@DarrenZLew Thank you!

**Pull request merged**
