### PR TITLE
Fix: issue 718, improve validation message for user profile name edit

### PR DESCRIPTION
**Pull request by danekshea**
Quick fix for https://github.com/OpenBeta/open-tacos/issues/718 with an added description of the regex. Didn't test the build due to not having auth available, might be overflow due to length of message but the responsive UI probably handles it find.

### CODE REVIEW

**Comment by vnugent** [comment]
can you please smoke test the change using the preview build?   https://open-tacos-aa73c08rd-openbeta-dev.vercel.app/

thanks!

**Comment by vnugent** [comment]
Screenshot 2023-04-07 at 5 54 32 AM

you're right - there's not enough room for the long error message.

**Comment by zichongkao** [comment]
I looked into this briefly to find a path forward.

I see several options:
1. Change the error message display to accommodate larger messages. We could move to a toast, or a tool-tip like modal that is displayed on top of the page content. It could perhaps auto-disappear after several seconds or once the error is fixed.
2. Break up `checkUsername` (https://github.com/OpenBeta/open-tacos/blob/d9f2d1a3011f4dfefb4861718840440eca24f3a7/src/js/utils.ts#L163) into its three constituent subrules:
- "First and last characters have to be alphanumeric",
- "User name can only consist of alphanumeric and special characters: '.', '-', '_'"
- "At most one special character is permitted"
each with its own check and dedicated error message. 
3. Try a shorter error message: 'Username must be alphanumeric, optionally separated by a ".", "-" or "_".'
4. Simplify the `checkUsername` constraints so that it is more easily explained. Eg. "All alphanumeric only", or "Alphanumeric and special characters (., /, -)" + "special characters not permitted in first and last"  (ie remove the "at most one special char" rule)

I'd favor 3 and 4. I feel like the current logic is somewhat hard to explain and fairly arbitrary. Perhaps "Only alphanumeric characters and ".", "_", "-" are permitted" would do.

**Comment by zichongkao** [comment]
@vnugent @danekshea What do y'all think?

**Comment by vnugent** [comment]
I'd be in favor of 3 and/or 4.  Like you said we can break down the validation into multiple tests, each showing their own shorter message.

**Comment by danekshea** [comment]
3 and 4 sound pretty logical @zichongkao !

**Comment by vnugent** [comment]
superseded by https://github.com/OpenBeta/open-tacos/pull/838

**Pull request closed without merging**
