### PR TITLE
Fixed infinite recurse when panning map

### PR DESCRIPTION
**Pull request by CocoisBuggy**
https://visgl.github.io/react-map-gl/docs/get-started/state-management#controlled-map

Before, you could not pan the map at all. Now the behavior seems to be as expected.

(Also added type annotation to getMapDivDimensions)

### CODE REVIEW

**Comment by vnugent** [comment]
The map is not maximized full height when I navigate away then go back.

To reproduce:
1. Search for Las Vegas
2. Click on an area dot on the map to bring up the popup
3. Click on the popup
4. Browser go back.  The map div is now shorter (screenshot)

---

Screen Shot 2022-05-13 at 1 57 46 PM

**Comment by vnugent** [comment]
Are you seeing this problem?  https://github.com/OpenBeta/open-tacos/issues/289

**Comment by CocoisBuggy** [comment]
#289 is the issue that this was supposed to fix, let me look into the responsive container

**Comment by CocoisBuggy** [comment]
Oh, that is not the correct solution. That reverts back to the infinite recurse

**Comment by vnugent** [comment]
> https://github.com/OpenBeta/open-tacos/issues/289 is the issue that this was supposed to fix, let me look into the responsive container
FYI, the MapBox GL component requires a pre-defined height hence the need for the hook to calculate the height.

**Comment by CocoisBuggy** [comment]
Bit of a head-scratcher

They have an internal event for listening to resizes [here](https://github.com/visgl/react-map-gl/blob/bb9f1f45d845421fef8c39c3b6c39a3426db3e52/src/mapbox/mapbox.ts#L565-L568) although, of course, this is just a wrapper for the mapbox-gl library... so it is really difficult to nail down exactly why it skips over our modification of the height prop.

```tsx
const mapRef = useRef(null)

  // Map seems to struggle responding to height changes after initial set
  useEffect(() => {
    if (mapRef.current !== null) {
      const map: MapboxMap = (mapRef.current as any)
      map.resize()
    }
  }, [height, mapRef])

  return (
    <Map
    ref={mapRef}
    ...
    />
```

There is a potential problem here; being that when resize events are dispatched resize() will be called twice. I would still expect it to be about as performant as it was before...

**Comment by vnugent** [comment]
Thanks for looking into this.  I've verified the preview build on large screen and mobile devtool.

**Pull request merged**
