### PR TITLE
Add the header for naviage to map

### PR DESCRIPTION
**Pull request by AQIB-NAWAB**
---
name: Pull request
about: Create a pull request
title:  add hero alert for "Find Climbings by State " at home page
labels: ''
assignees: ''

---

## What type of PR is this?(check all applicable)
- [ x] optimization

## Description
Add the header for naviage to map

### Related Issues

Issue # #1177

### What this PR achieves

Add a button to navigate the page to search the locations by state

### Screenshots, recordings

image

### CODE REVIEW

**Comment by AQIB-NAWAB** [comment]
fix #1177

**Review by clintonlunn — CHANGES_REQUESTED** [review]
Hi @AQIB-NAWAB it looks like you've still got those linting errors. 

Can you run `yarn run lint` in your local terminal on this branch and fix those warnings? No need to create another pr, we can squash the changes when merging.

**Comment by clintonlunn** [comment]
@vnugent would you mind approving the vercel deploy for this?

**Comment by AQIB-NAWAB** [comment]
@clintonlunn Oops forgot to run that command , Just resolved the linting errors 
You can review it now

**Comment by clintonlunn** [comment]
Hi @AQIB-NAWAB i added a few comments. In addition can you pull in the latest changes. You'll see that `LandingHero.tsx` changed recently in this pr https://github.com/OpenBeta/open-tacos/pull/1195/files#diff-f2977183e5d7a5b514e34954a79abf75e822bf3c313b39c9e4f9bb9a2f55fe89

I think it's fine to add the `HeroAlert` back but account for a variable number of `HeroAlert`s

**Comment by vnugent** [comment]
Superseded by PR #1196

**Pull request closed without merging**
