### PR TITLE
subtract forYou values from total to make pie chart make sense

### LINKED ISSUE #276: "Climbs For You" pie chart does not display correct information
the pie chart in the "Climbs For You" section of a crag finder page does not seem to display correct information. 

image

### PR DESCRIPTION
**Pull request by clintonlunn**
addresses issue #276 

gray represents the leftover climbs that are not in the desired range, and the green highlighted are the climbs that are within the desired range. As per @vnugent's comment down below, I also changed the color of the pie chart to match the difficulty table colors.

**Before**:
image

**After**:
image

### CODE REVIEW

**Comment by MichaelDimmitt** [comment]
hmm, what was the before behavior?

**Comment by clintonlunn** [comment]
> hmm, what was the before behavior?

@MichaelDimmitt good point, I should have included the before behavior! It basically displayed (total / forYou), so in the first row it would be (3 / 2), which would not make too much sense to the user. 

Before behavior:
image

**Comment by MichaelDimmitt** [comment]
I see you did not fix the number,
you fixed the pie chart to show an appropriate ratio,

you get claps 👏

**Comment by vnugent** [comment]
@clintonlunn do you think we should change the color of the active pie to light green, same as user band color on the distribution table?

**Comment by clintonlunn** [comment]
@vnugent Ok, I changed the colors to match the difficulty table (see above in original post for screenshot). I also matched the opacity values from the difficulty tables (to 70% opacity). What do you think?

Also, I added a snapshot test to verify that the piecharts were correctly rendered, which meant I had to add an additional dev dependency. I hope that's okay! Let me know if you don't think it serves much purpose and I will remove it.

**Comment by vnugent** [comment]
> Also, I added a snapshot test to verify that the piecharts were correctly rendered, which meant I had to add an additional dev dependency. I hope that's okay! Let me know if you don't think it serves much purpose and I will remove it.

Fine with me.  And thanks for writing tests.  I think snapshot testing have their place when when we can't easily test D3 or WebGL components.

**Comment by vnugent** [comment]
I've just realized the low contrast between the gray the secondary color makes it a bit hard to see when the number is small.  But let's revisit colors/theming later in another PR  :)

---
Screen Shot 2022-04-24 at 8 27 49 PM

**Comment by clintonlunn** [comment]
> I've just realized the low contrast between the gray the secondary color makes it a bit hard to see when the number is small. But let's revisit colors/theming later in another PR :)
> 
> Screen Shot 2022-04-24 at 8 27 49 PM

@vnugent agreed the contrast is pretty low. There is a current issue open in #216 that it can probably be addressed in? To me this would be probably also not be compliant from a a11y standpoint.

**Pull request merged**
