### PR TITLE
Set up user metadata handling

### LINKED ISSUE #320: Endpoints for fetching/updating user metadata
Using auth0 management API to fetch/update user metadata. Will need to request the management api audience and additional scopes in next-auth config

### PR DESCRIPTION
**Pull request by nthh**
Adds API routes for auth0 user metadata fetching/updating and simple demo profile page

### Test plan
Log in 
Navigate manually to /profile 
Use the input to update the name
Refresh and confirm it persists

Fixes #320

### CODE REVIEW

**Comment by vnugent** [comment]
I can't log in because Vercel preview url changes for each PR. Can we use wildcard for `Allowed Callback URLs` and others?

*edit:  it seems possible:  https://github.com/vercel/vercel/discussions/4811

Screen Shot 2022-05-20 at 12 24 20 PM

**Comment by nthh** [comment]
> I can't log in because Vercel preview url changes for each PR. Can we use wildcard for `Allowed Callback URLs` and others?
> 
> *edit: it seems possible: [vercel/vercel#4811](https://github.com/vercel/vercel/discussions/4811)

I thought they didn't allow wildcards in callback URLs but I guess they do... set to `https://*-openbeta-dev.vercel.app` and it seems to work

**Comment by vnugent** [comment]
I verified a couple things:
- [x] Login, update name, logout, relogin. Name persists.
- [x] Login, get 401 when trying to access /api/profile in a different browser, with `curl` 
- [ ] Logout, access /profile page.  It's accessible.  Is this normal?  Let's say we want to protect `/account` (user account page).  How do we force the login prompt?

**Comment by nthh** [comment]
I added a `withAuth` HOC (20f221b6e3e853da413d54ff42080964c9b41829) which redirects to the login page if a protected route is reached without a valid session. If you try again with the[ latest deployment](https://open-tacos-kx4dh6z9d-openbeta-dev.vercel.app/) it should work.

**Pull request merged**
