### PR TITLE
fix: upgrade ts-standard & fit errors

### PR DESCRIPTION
**Pull request by vnugent**
---
name: Pull request
about: Create a pull request
title: ''
labels: ''
assignees: ''

---

## What type of PR is this?(check all applicable)
- [x] refactor
- [ ] feature
- [x] bug fix
- [ ] documentation
- [ ] optimization
- [ ] other

### Related Issues

Issue #787 

### What this PR achieves
- [x] upgrade ts-standard.
- [x] fix misconfiguration in package.json which caused a rules not being checked
- [x] fix all errors
- [x] fix unit tests

### CODE REVIEW

**Comment by musoke** [comment]
a huge PR!

**Comment by vnugent** [comment]
> a huge PR!

It is! ts-standard linter was misconfigured in package.json so a lot of formatting issues fell through the crack.  For example spaces are required between | operator 

```javascript
Promise<IUserProfile | null> 
```
or 
Screenshot 2023-09-22 at 3 36 34 PM

**Comment by enapupe** [comment]
hi there, I was looking into some strange behaviour when uploading photos and noticed this PR seems to be the cause.
why did you replace `await` with `void` generally across the files? 
the general uploader now does not wait (`await`!!) the upload to finish before giving the "upload complete" feedback.

**Comment by vnugent** [comment]
> hi there, I was looking into some strange behaviour when uploading photos and noticed this PR seems to be the cause. why did you replace `await` with `void` generally across the files? the general uploader now does not wait (`await`!!) the upload to finish before giving the "upload complete" feedback.

Good catch.  I was watching another user uploading photos earlier and saw similar behavior.  In trying to fix linting errors I think this PR has introduced a bug.

**Comment by vnugent** [comment]
@enapupe thanks for reporting the bug.  The app now waits for photo uploaded to be completed.  Fixed in https://github.com/OpenBeta/open-tacos/pull/990

**Comment by vnugent** [comment]
@all-contributors add @enapupe for bug

**Pull request merged**
