### PR TITLE
fixed typo in contributor URL

### PR DESCRIPTION
**Pull request by ygingras**

### CODE REVIEW

**Comment by vnugent** [comment]
@allcontributors please add ygingras for ideas and content

**Comment by vnugent** [comment]
@ygingras the bot reads the website url from your github profile, which has a typo.  Can you try updating your github profile then enter this comment: `@allcontributors please add ygingras for ideas and content`

**Comment by ygingras** [comment]
Good catch! I wonder how long I have been showing the wrong URL on my github profile.

@allcontributors please add ygingras for ideas and content

**Comment by vnugent** [comment]
@allcontributors please add ygingras for ideas and content

**Comment by vnugent** [comment]
manually removed user from .all-contributorsrc
@allcontributors please add ygingras for ideas and content

**Comment by vnugent** [comment]
@allcontributors please add ygingras for ideas and content

**Pull request merged**
