### PR TITLE
Coco/layout changes

### PR DESCRIPTION
**Pull request by CocoisBuggy**
Some proposals to update area / subarea explorer, and  crag viewer.

Looking at the https://www.figma.com/file/VBJaQSdUlIRMYeMnBENmn1/Wireframe-OpenBeta?node-id=0%3A1 specification and the screenshots linked in #291 And I'm hoping I'm somewhat on the ball here.

## Area explorer

image

## Crag browse

image

Would love to here some thoughts on where these layouts might be lacking

### CODE REVIEW

**Comment by vnugent** [comment]
@CocoisBuggy going forward if you want your PR to trigger an automatic preview deployment (without waiting for me or and admin to approve), you can clone this project and create a working branch, then push.  

The additional check in Vercel prevents PRs created from forked repos from potentially exposing protected runtime env vars.  Project team members have higher implicit trust level, hence their PRs don't require approval to build.

**Comment by vnugent** [comment]
I really like @BeaulieuC's design as in your 2nd screenshot, the crag browser.  However, she made those suggestions before we introduced the map.  With the map, things do look a bit imbalanced.   I'm not sure if I can come up with a better suggestions.  Maybe @BeaulieuC can help us out.

**Comment by vnugent** [comment]
@CocoisBuggy also, can you please rebase so that the PR history is cleaner/shorter? thanks!

**Comment by CocoisBuggy** [comment]
I'll try and think of a way to balance the design a bit better. @BeaulieuC Actually did solve the table problem with a slightly more elegant column layout. I'll take another go at implementing that more faithfully

**Comment by CocoisBuggy** [comment]
Closing this to do some clean-up.

**Pull request closed without merging**
