### PR TITLE
Updated public CDN to new media server [ fixes #1013] 

### LINKED ISSUE #1013: Use new media servers
**What would you like to be able to do? Please describe.**
We now have 2 new media services, `media-stg.openbeta.io` and `media.openbeta.io`. Update the code to use the new url.

### Contributor To-do:
- [ ] In .env update  `NEXT_PUBLIC_CDN_URL` to **https://media-stg.openbeta.io**

### Admin to-do:
- [ ] Update NEXT_PUBLIC_CND_URL in Vercel dashboard to media.openbeta.io

Related issue: https://github.com/OpenBeta/open-tacos/issues/944

**How important is this to you** (Please pick one)
- Important

### PR DESCRIPTION
**Pull request by ShravaniRoy**
---
name: Updated public CDN to new media server 
about: Create a pull request
title: ''
labels: ''
assignees: ''

---

## What type of PR is this?(check all applicable)
- [ ] refactor
- [ ] feature
- [ ] bug fix
- [ ] documentation
- [ ] optimization
- [ ] other

## Description

As there are new media servers in place, updated the URL.

### Related Issues

Issue #1013

### What this PR achieves

A simple URL update.

### CODE REVIEW

**Comment by enapupe** [comment]
It seems next config must be updated as well, however, I'm not sure it's the right move, since images will be processed by two media servers.
https://github.com/ShravaniRoy/open-tacos/blob/updateToNewMediaServer/next.config.js#L3

**Comment by vnugent** [comment]
@enapupe did you see this option? https://nextjs.org/docs/pages/api-reference/next-config-js/images
I think we will have add a global loader and update all instances of Image.

**Comment by enapupe** [comment]
I've opened another PR to work on this issue since it became a bit tricky: https://github.com/OpenBeta/open-tacos/pull/1019

**Comment by vnugent** [comment]
@ShravaniRoy I didn't anticipate the additional impact of introducing our own media services.  Sorry I have to close your PR  since #1019 address other related issues.

**Comment by vnugent** [comment]
@all-contributors add @ShravaniRoy for code

**Pull request closed without merging**
